version: '3.6'
services:

  envoy-proxy:
    container_name: envoy-proxy
    depends_on:
      - proxy-client
    image: fydeinc/envoyproxy-centos:latest
    networks:
      - fyde
    ports:
      # Publicly exposed Access Proxy port must match in the management console
      - "8000:8000"
    restart: unless-stopped

  proxy-client:
    container_name: proxy-client
    environment:
      # Update with Proxy Enrollment Link
      - FYDE_ENROLLMENT_TOKEN=<paste here your Proxy Enrollment Link>
    image: fydeinc/fydeproxy-centos:latest
    networks:
      - fyde
    restart: unless-stopped

networks:
  fyde:
    name: fyde
