# Docker compose Fyde Access Proxy
---
version: '3'
services:

  envoy-proxy:
    container_name: envoy-proxy
    depends_on:
      - fyde-orchestrator
    environment:
      - FYDE_PROXY_HOST=fyde-orchestrator
      - FYDE_PROXY_PORT=50051
    image: fydeinc/envoyproxy-centos:latest
    networks:
      - fyde
    ports:
      # Publicly exposed Fyde Access Proxy port
      # Host port must match the one defined in Fyde Enterprise Console
      - "443:8000"
    restart: unless-stopped

  fyde-orchestrator:
    container_name: fyde-orchestrator
    environment:
      # Update with Fyde Access Proxy enrollment link
      - FYDE_ENROLLMENT_TOKEN=<paste here your Fyde Access Proxy enrollment link>
    image: fydeinc/fydeproxy-centos:latest
    networks:
      - fyde
    restart: unless-stopped

networks:
  fyde:
    name: fyde
