version: '3.6'
services:

  envoy-proxy:
    container_name: envoy-proxy
    depends_on:
      - fyde-orchestrator
    image: fydeinc/envoyproxy-centos:latest
    networks:
      - fyde
    ports:
      # Publicly exposed Fyde Access Proxy port
      # Must match the one define in Fyde Enterprise Console
      - "8000:8000"
    restart: unless-stopped

  fyde-orchestrator:
    container_name: fyde-orchestrator
    environment:
      # Update with Fyde Access Proxy enrollment link
      - FYDE_ENROLLMENT_TOKEN=<paste here your Fyde Access Proxy enrollment link>
    image: fydeinc/fydeproxy-centos:latest
    networks:
      fyde:
        aliases:
          # This name cannot be changed for now
          # Envoy proxy uses it to find the Fyde Proxy Orchestrator
          - proxy-client
    restart: unless-stopped

networks:
  fyde:
    name: fyde
