# Envoy Proxy
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy
  annotations:
    # Adjust according to your kubernetes cluster environment
    # https://kubernetes.io/docs/concepts/services-networking/#publishing-services-service-types
spec:
  ports:
    - name: envoy-proxy
      port: 8000
      protocol: TCP
      targetPort: envoy
  selector:
    app: envoy-proxy
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-proxy
  template:
    metadata:
      name: envoy-proxy
      labels:
        app: envoy-proxy
    spec:
      containers:
        - name: envoy-proxy
          image: fydeinc/envoyproxy-centos:latest
          imagePullPolicy: Always
          env:
            - name: LOGLEVEL
              value: info
            - name: COMPONENTLOGLEVEL
              value: grpc:debug,config:debug
          ports:
            - name: envoy
              containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 64M
            limits:
              cpu: 200m
              memory: 128M
          readinessProbe:
            tcpSocket:
              port: envoy
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: envoy
            initialDelaySeconds: 30
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 3
