# Site settings
remote_theme: pmarsceill/just-the-docs
title: Barracuda CloudGen Access Docs
baseurl: /docs
url: https://fyde.github.io
description: Documentation for the Barracuda CloudGen Access product
permalink: pretty
color_scheme: fyde

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links_new_tab: true
aux_links:
  "Access Console":
    - "//enterprise.fyde.com"
  "Service Status":
    - "//status.fyde.com"
  "CloudGen Access":
    - "//www.barracuda.com/products/cloudgen-access"
